# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  - push
  - pull_request

name: tests

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,  r: 'release'}
          - {os: macOS-latest,    r: 'release'}
          ##- {os: ubuntu-20.04,    r: 'release'}
          ##- {os: ubuntu-latest,   r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        if: runner.os == 'Linux'
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(pkgdir = './nimbleHMC', dependencies = TRUE),
                                                   ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-


      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04", "./nimbleHMC"))')
          sudo apt-get install libcurl4-openssl-dev  # needed for R pkg curl -> covr

      - name: Install dependencies
        run: source('install_requirements.R')
        shell: Rscript {0}

      - name: Install nimbleHMC (Windows)
        if: runner.os == 'Windows'
        run: RCMD INSTALL --install-tests nimbleHMC

      - name: Install nimbleHMC
        if: runner.os != 'Windows'
        run: R CMD INSTALL --install-tests nimbleHMC

      - name: Run tests
        run: source('run_tests.R')
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
